/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Calendar;
import java.util.GregorianCalendar;

public class Clock extends javax.swing.JFrame 
{
    int TimeRun = 0;
    int xMouse;
    int yMouse;
    
    public Clock() 
    {
        initComponents();
        //This is where you start programming your clock
        new Thread ()
        {
            public void run ()
            {
                while (TimeRun == 0) 
                {
                    Calendar Cal = new GregorianCalendar();
                    
                    int hour = Cal.get(Calendar.HOUR);
                    int minute = Cal.get(Calendar.MINUTE);
                    int second = Cal.get(Calendar.SECOND);
                    int AM_PM = Cal.get(Calendar.AM_PM);
                    
                    String Day_Night = "";
                    
                    if (AM_PM == 1)
                    {
                     Day_Night = "PM";
                    }
                    
                    else 
                    {
                     Day_Night = "AM";   
                    }
                    
                    String time = hour + " : " + minute + " : " + second + " " + Day_Night;
                    ClockDisplay.setText(time);
                }
        }
    } .start();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClockDisplay = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        CloseWindow = new javax.swing.JLabel();
        Dragging = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClockDisplay.setFont(new java.awt.Font("DS-Digital", 1, 60)); // NOI18N
        ClockDisplay.setForeground(new java.awt.Color(0, 165, 255));
        getContentPane().add(ClockDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 440, 140));

        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 12, 10, 10));

        CloseWindow.setForeground(new java.awt.Color(255, 255, 255));
        CloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseWindowMouseClicked(evt);
            }
        });
        getContentPane().add(CloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 11, 10, 10));

        Dragging.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DraggingMouseDragged(evt);
            }
        });
        Dragging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DraggingMousePressed(evt);
            }
        });
        getContentPane().add(Dragging, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clock Background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseWindowMouseClicked
        //This is for Closing Window
        System.exit(0);
    }//GEN-LAST:event_CloseWindowMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        //This is for minimize
        this.setState(Clock.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void DraggingMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggingMouseDragged
        // This is for Part 1 of dragging our windows
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
        
        System.out.println(x + "," + y);
    }//GEN-LAST:event_DraggingMouseDragged

    private void DraggingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggingMousePressed
        // This is for Part 2 of dragging our windows
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_DraggingMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClockDisplay;
    private javax.swing.JLabel CloseWindow;
    private javax.swing.JLabel Dragging;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
